Repository andela/selene-ah-frontend, pull requests merged in 2019-01, with the labels that each got.

#4 #161779820 Chore setup sass
  config/filePaths.js
  config/webpack.base.js
  config/webpack.dev.js
  config/webpack.prod.js
  package-lock.json
  package.json
  server.js
  src/assets/scss/base.scss
  src/components/Footer.js
  src/components/Header.js
  src/hoc/Aux.js
  src/index.js
  webpack.config.js
Labels: Needs Review, merge first

#6 #163022157 Set up Eslint
  .eslintignore
  .eslintrc
  package-lock.json
  package.json
  server.js
  src/containers/App.js
  src/index.js
Labels: ready

#3 #161779819 router configured
  .editor.config
  .eslintrc
  package-lock.json
  src/components/Main.js
  src/containers/App.js
  src/containers/Home.js
  src/index.js
  src/routes.js
  tests/App.spec.js
Labels: Needs Review

#10 #161779822 - Implement signup feature
  .babelrc
  config/webpack.dev.js
  jest.config.js
  package-lock.json
  package.json
  setup/enzymeSetup.js
  src/actions/authAction/__test__/signup.spec.js
  src/actions/authAction/signup.js
  src/assets/fonts/Raleway/OFL.txt
  src/assets/fonts/Raleway/Raleway-Black.ttf
  src/assets/fonts/Raleway/Raleway-BlackItalic.ttf
  src/assets/fonts/Raleway/Raleway-Bold.ttf
  src/assets/fonts/Raleway/Raleway-BoldItalic.ttf
  src/assets/fonts/Raleway/Raleway-ExtraBold.ttf
  src/assets/fonts/Raleway/Raleway-ExtraBoldItalic.ttf
  src/assets/fonts/Raleway/Raleway-ExtraLight.ttf
  src/assets/fonts/Raleway/Raleway-ExtraLightItalic.ttf
  src/assets/fonts/Raleway/Raleway-Italic.ttf
  src/assets/fonts/Raleway/Raleway-Light.ttf
  src/assets/fonts/Raleway/Raleway-LightItalic.ttf
  src/assets/fonts/Raleway/Raleway-Medium.ttf
  src/assets/fonts/Raleway/Raleway-MediumItalic.ttf
  src/assets/fonts/Raleway/Raleway-Regular.ttf
  src/assets/fonts/Raleway/Raleway-SemiBold.ttf
  src/assets/fonts/Raleway/Raleway-SemiBoldItalic.ttf
  src/assets/fonts/Raleway/Raleway-Thin.ttf
  src/assets/fonts/Raleway/Raleway-ThinItalic.ttf
  src/assets/scss/components/form/_form.scss
  src/containers/Auth/Login/Login.js
  src/containers/Auth/Login/_login.scss
  src/containers/Auth/SignUp/SignUp.js
  src/containers/Auth/SignUp/SignUpContainer.js
  src/containers/Auth/SignUp/SignUpContainer.js~HEAD
  src/containers/Auth/SignUp/__test__/signUp.spec.js
  src/containers/Auth/SignUp/__test__/signupContainer.spec.js
  src/containers/Auth/SignUp/helpers/signupValidations.js
  src/containers/Auth/SignUp/helpers/signupValidations.spec.js
  src/containers/Auth/SignUp/signup.scss
  src/containers/Auth/SignUp/style/signup.scss
  src/containers/Form/FormContainer.js
  src/containers/Form/FormWrapper.js
  src/containers/Form/__test__/formWrapper.spec.js
  src/containers/Home.js
  src/containers/__tests__/App.spec.js
  src/containers/__tests__/Home.spec.js
  src/helpers/history.js
  src/helpers/store/utility.js
  src/helpers/store/utility.spec.js
  src/helpers/test/fakeStore.js
  src/helpers/validationHelpers/validations.js
  src/helpers/validationHelpers/validations.spec.js
  src/reducers/authReducers/__test__/signup.spec.js
  src/reducers/authReducers/signup.js
  src/routes.js
Labels: Needs Review

#15 chore(signup): refactor input component props data
  config/webpack.base.js
  src/actions/authAction/__test__/signup.spec.js
  src/assets/scss/components/form/_form.scss
  src/assets/vendor.min.css
  src/containers/Auth/Login/Login.js
  src/containers/Auth/Login/_login.scss
  src/containers/Auth/SignUp/SignUp.js
  src/containers/Auth/SignUp/__test__/signUp.spec.js
  src/containers/Auth/SignUp/helpers/signupValidations.js
  src/containers/Auth/SignUp/style/signup.scss
  src/containers/Form/FormContainer.js
  src/containers/Form/FormWrapper.js
  src/index.js
Labels: Needs Review

#13 #161779825 implement social auth for Google & Facebook
  .codeclimate.yml
  config/webpack.base.js
  package-lock.json
  package.json
  src/actions/authAction/__test__/socialAuth.spec.js
  src/actions/authAction/actionTypes.js
  src/actions/authAction/socialAuth.js
  src/assets/scss/components/form/_form.scss
  src/components/utilities/SocialButtons/SocialButton.js
  src/components/utilities/SocialButtons/SocialButton.spec.js
  src/components/utilities/index.js
  src/containers/Auth/Login/Login.js
  src/containers/Auth/Login/__test__/login.spec.js
  src/containers/Auth/SignUp/SignUp.js
  src/containers/Auth/SocialAuth/SocialButtons.js
  src/containers/Auth/SocialAuth/VerifyAuth.js
  src/containers/Auth/SocialAuth/__tests__/SocialButtons.spec.js
  src/containers/Auth/SocialAuth/__tests__/VerifyAuth.spec.js
  src/reducers/authReducers/__test__/sociaAuthReducer.spec.js
  src/reducers/authReducers/socialAuthReducer.js
  src/reducers/index.js
  src/routes.js
  src/store.js
Labels: Needs Review, ready

#16 #161779823 implement reset password feature
  src/actions/authAction/__test__/resetPassword.spec.js
  src/actions/authAction/__test__/updatePassword.spec.js
  src/actions/authAction/actionTypes.js
  src/actions/authAction/resetPassword.js
  src/actions/authAction/updatePassword.js
  src/assets/images/sendemail.svg
  src/assets/images/updatepassword.svg
  src/assets/scss/components/form/_form.scss
  src/assets/vendor.min.css
  src/components/pages/NoMatch/NoMatch.js
  src/components/utilities/Button/Button.js
  src/containers/Auth/Login/Login.js
  src/containers/Auth/Login/_login.scss
  src/containers/Auth/ResetPassword/ResetPassword.js
  src/containers/Auth/ResetPassword/ResetPassword.scss
  src/containers/Auth/ResetPassword/UpdatePassword.js
  src/containers/Auth/ResetPassword/__test__/resetPassword.spec.js
  src/containers/Auth/ResetPassword/__test__/updatePassword.spec.js
  src/containers/Auth/SignUp/SignUp.js
  src/containers/Auth/SignUp/style/signup.scss
  src/containers/Form/FormContainer.js
  src/containers/Form/FormWrapper.js
  src/containers/Form/__test__/formContainer.spec.js
  src/reducers/authReducers/__test__/resetPassword.spec.js
  src/reducers/authReducers/__test__/updatePassword.spec.js
  src/reducers/authReducers/resetPassword.js
  src/reducers/authReducers/updatePassword.js
  src/reducers/index.js
  src/routes.js
Labels: Needs Review

#20 #163286827 fixed login and signup page responsiveness
  .env.sample
  src/assets/scss/base.scss
  src/assets/scss/components/_badges.scss
  src/assets/scss/components/_cards.scss
  src/assets/scss/components/_chips.scss
  src/assets/scss/components/_collapsible.scss
  src/assets/scss/components/_color-classes.scss
  src/assets/scss/components/_color-variables.scss
  src/assets/scss/components/_datepicker.scss
  src/assets/scss/components/_dropdown.scss
  src/assets/scss/components/_global.scss
  src/assets/scss/components/_grid.scss
  src/assets/scss/components/_preloader.scss
  src/assets/scss/components/_pulse.scss
  src/assets/scss/components/_sidenav.scss
  src/assets/scss/components/_tabs.scss
  src/assets/scss/components/_tapTarget.scss
  src/assets/scss/components/_timepicker.scss
  src/assets/scss/components/_toast.scss
  src/assets/scss/components/_tooltip.scss
  src/assets/scss/components/_transitions.scss
  src/assets/scss/components/_variables.scss
  src/assets/scss/components/button/_button.scss
  src/assets/scss/components/form/_form.scss
  src/containers/Auth/Login/Login.js
  src/containers/Auth/Login/_login.scss
  src/containers/Auth/ResetPassword/ResetPassword.js
  src/containers/Auth/ResetPassword/ResetPassword.scss
  src/containers/Auth/SignUp/SignUp.js
  src/containers/Auth/SignUp/style/signup.scss
  src/containers/Auth/SocialAuth/SocialButtons.js
  src/containers/Auth/SocialAuth/VerifyAuth.js
  src/containers/Form/FormContainer.js
  src/containers/Form/FormWrapper.js
  src/containers/Form/__test__/formWrapper.spec.js
Labels: Needs Review, merge first, ready

#19 #163266250 Implement article reading page
  package-lock.json
  package.json
  src/actions/articleAction/__tests__/articleViewAction.spec.js
  src/actions/articleAction/actionTypes.js
  src/actions/articleAction/articleView.js
  src/assets/scss/base.scss
  src/assets/scss/base/_utilities.scss
  src/assets/scss/components/form/_form.scss
  src/assets/scss/components/skeleton/_mixins.scss
  src/assets/scss/components/skeleton/_skeleton.scss
  src/assets/scss/components/skeleton/_variables.scss
  src/components/misc/ArticleLoader/ArticleLoader.js
  src/components/misc/ArticleLoader/__test__/ArticleLoader.spec.js
  src/components/utilities/Navbar/Navbar.js
  src/components/utilities/Navbar/Navbar.scss
  src/components/utilities/Navbar/NavbarItem.js
  src/components/utilities/SideNav/SideNav.js
  src/components/utilities/SideNav/SideNav.scss
  src/components/utilities/SideNav/SideNavItem.js
  src/components/utilities/index.js
  src/config/index.js
  src/containers/Article/Article.js
  src/containers/Article/ArticleView.js
  src/containers/Article/ArticleView.scss
  src/containers/Article/__tests__/Article.spec.js
  src/containers/Article/__tests__/ArticleView.spec.js
  src/helpers/__tests__/dateStamp.spec.js
  src/helpers/dateStamp.js
  src/reducers/articleViewReducer/__tests__/articleViewReducer.spec.js
  src/reducers/articleViewReducer/articleView.js
  src/reducers/index.js
  src/routes.js
Labels: Needs Review

#23 #163317134 user is able to view landing page.
  config/webpack.dev.js
  package.json
  src/actions/authAction/actionTypes.js
  src/assets/fonts/Raleway/OFL.txt
  src/assets/images/bell.svg
  src/assets/images/edit-3.svg
  src/assets/scss/Home/styles.scss
  src/assets/scss/base/_utilities.scss
  src/assets/scss/components/_tapTarget.scss
  src/assets/scss/components/_transitions.scss
  src/assets/scss/components/navbar/_navbar.scss
  src/components/misc/Hero/Hero.js
  src/components/misc/Hero/Hero.scss
  src/components/misc/Hero/hero.spec.js
  src/components/misc/index.js
  src/components/utilities/Card/Card.js
  src/components/utilities/Card/CardParent.js
  src/components/utilities/Card/Cards.scss
  src/components/utilities/Card/card.spec.js
  src/components/utilities/Card/cardParent.spec.js
  src/components/utilities/Navbar/Navbar.js
  src/components/utilities/Navbar/Navbar.scss
  src/components/utilities/Navbar/NavbarItem.js
  src/components/utilities/Navbar/navBar.spec.js
  src/components/utilities/SideNav/SideNav.js
  src/components/utilities/SideNav/SideNav.scss
  src/components/utilities/SideNav/SideNavItem.js
  src/components/utilities/SideNav/sideNav.spec.js
  src/components/utilities/Tag/Tag.js
  src/components/utilities/Tag/Tag.scss
  src/components/utilities/Tag/TagParent.js
  src/components/utilities/Tag/tag.spec.js
  src/components/utilities/Tag/tagParent.spec.js
  src/components/utilities/index.js
  src/containers/App.js
  src/containers/Article/Article.js
  src/containers/Article/__tests__/Article.spec.js
  src/containers/Auth/Login/_login.scss
  src/containers/Home.js
  src/containers/Home/Home.js
  src/containers/Home/home.spec.js
  src/containers/Home/homeActionCreators.js
  src/containers/Home/homeActionCreators.spec.js
  src/containers/__tests__/Home.spec.js
  src/helpers/utilities/utilities.js
  src/index.html
  src/reducers/authReducers/__test__/home.spec.js
  src/reducers/authReducers/home.js
  src/reducers/index.js
Labels: Needs Review, merge first

#22 #161779831 implement like and dislike functionality
  .eslintrc
  config/webpack.prod.js
  package-lock.json
  package.json
  src/actions/reactionActions/__test__/likeArticle.spec.js
  src/actions/reactionActions/actionTypes.js
  src/actions/reactionActions/likeArticleActions.js
  src/assets/images/icons/Group 1.svg
  src/assets/images/icons/like(no-like-state).svg
  src/assets/images/icons/like-state.png
  src/assets/images/icons/like-state.svg
  src/assets/images/icons/no-like-state.svg
  src/assets/scss/base.scss
  src/assets/scss/base/_typography.scss
  src/assets/scss/base/_utilities.scss
  src/assets/scss/components/_navbar.scss
  src/assets/scss/components/navbar/_navbar.scss
  src/components/pages/NoMatch/NoMatch.scss
  src/components/utilities/Card/Card.js
  src/components/utilities/Card/Cards.scss
  src/components/utilities/Card/card.spec.js
  src/components/utilities/Navbar/Navbar.js
  src/containers/Article/Article.js
  src/containers/Article/ArticleView.scss
  src/containers/Article/__tests__/Article.spec.js
  src/containers/Auth/Login/Login.js
  src/containers/Auth/ResetPassword/ResetPassword.js
  src/containers/Auth/ResetPassword/UpdatePassword.js
  src/containers/Auth/SignUp/SignUp.js
  src/containers/Auth/SignUp/style/signup.scss
  src/containers/Home/Home.js
  src/containers/Home/home.spec.js
  src/containers/Reaction/LikeReaction.js
  src/containers/Reaction/__test__/helpers.spec.js
  src/containers/Reaction/__test__/likeReaction.spec.js
  src/containers/Reaction/helpers.js
  src/containers/Reaction/likeReaction.scss
  src/helpers/validationHelpers/__test__/decodeToken.spec.js
  src/helpers/validationHelpers/__test__/validations.spec.js
  src/helpers/validationHelpers/decodeToken.js
  src/reducers/index.js
  src/reducers/reactionReducers/__test__/likeArticle.spec.js
  src/reducers/reactionReducers/likearticleReactions.js
  src/routes.js
Labels: Needs Review

#18 #161779827 Implement feature for creating articles
  package-lock.json
  package.json
  src/actions/articles/__test__/articleActions.spec.js
  src/actions/articles/__test__/categoryActions.spec.js
  src/actions/articles/__test__/imageUploadAction.spec.js
  src/actions/articles/articleActionTypes.js
  src/actions/articles/articleActions.js
  src/actions/articles/categoryActionTypes.js
  src/actions/articles/categoryActions.js
  src/actions/articles/imageUploadActionTypes.js
  src/actions/articles/imageUploadActions.js
  src/actions/articles/index.js
  src/assets/scss/abstracts/_variables.scss
  src/assets/scss/base.scss
  src/assets/scss/components/editor/editorContainer.scss
  src/assets/scss/components/select/select.scss
  src/components/Article/CreateArticle.js
  src/components/Article/__test__/CreatArticle.spec.js
  src/components/NavBar/NavBar.js
  src/components/NavBar/__test__/NavBar.spec.js
  src/components/NavBar/_navbar.scss
  src/components/NavBar/_variables.scss
  src/components/TextEditor/Formatters/FormatHelper.js
  src/components/TextEditor/Formatters/__test__/FormatHelper.spec.js
  src/components/TextEditor/TextEditor.js
  src/components/TextEditor/__test__/TextEditor.spec.js
  src/components/TextEditor/__test__/editorSerializer.spec.js
  src/components/TextEditor/editorSerializer.js
  src/components/utilities/Button/Button.js
  src/components/utilities/Select/Select.js
  src/components/utilities/Select/Select.spec.js
  src/helpers/fileReader.js
  src/helpers/validationHelpers/__test__/validations.spec.js
  src/helpers/validationHelpers/validations.js
  src/index.html
  src/reducers/__test__/articleReducers.spec.js
  src/reducers/__test__/categoryReducer.spec.js
  src/reducers/__test__/imageUploadReducer.spec.js
  src/reducers/__test__/login.spec.js
  src/reducers/__test__/signup.spec.js
  src/reducers/__test__/sociaAuthReducer.spec.js
  src/reducers/articleReducers/articleReducers.js
  src/reducers/articleReducers/categoryReducer.js
  src/reducers/articleReducers/imageUploadReducers.js
  src/reducers/index.js
  src/routes.js
Labels: Needs Review

#24 Fixes general bug
  __mocks__/decodedUser.js
  config/webpack.prod.js
  package-lock.json
  package.json
  src/actions/authAction/__test__/socialAuth.spec.js
  src/actions/authAction/signup.js
  src/actions/authAction/socialAuth.js
  src/assets/images/almost_done.svg
  src/assets/images/icons/like(no-like-state).svg
  src/assets/images/icons/log-out.svg
  src/assets/scss/base/_utilities.scss
  src/assets/scss/components/button/_button.scss
  src/assets/scss/components/form/_form.scss
  src/assets/scss/components/skeleton/_skeleton.scss
  src/components/Article/CreateArticle.js
  src/components/Article/article.scss
  src/components/NavBar/NavBar.js
  src/components/NavBar/__test__/NavBar.spec.js
  src/components/NavBar/_navbar.scss
  src/components/NavBar/_variables.scss
  src/components/TextEditor/Formatters/FormatHelper.js
  src/components/TextEditor/TextEditor.js
  src/components/TextEditor/__test__/TextEditor.spec.js
  src/components/pages/EmailVerification/EmailVerification.js
  src/components/pages/EmailVerification/EmailVerification.scss
  src/components/pages/EmailVerification/__tests__/EmailVerification.spec.js
  src/components/utilities/BackDrop/BackDrop.js
  src/components/utilities/BackDrop/BackDrop.scss
  src/components/utilities/BackDrop/__tests__/BackDrop.spec.js
  src/components/utilities/Card/Card.js
  src/components/utilities/Navbar/Navbar.js
  src/components/utilities/Navbar/Navbar.scss
  src/components/utilities/Navbar/navBar.spec.js
  src/components/utilities/SideNav/SideNav.js
  src/components/utilities/Tag/Tag.js
  src/containers/Article/Article.js
  src/containers/Article/__tests__/Article.spec.js
  src/containers/Auth/Login/_login.scss
  src/containers/Auth/ResetPassword/ResetPassword.js
  src/containers/Auth/ResetPassword/ResetPassword.scss
  src/containers/Auth/ResetPassword/UpdatePassword.js
  src/containers/Auth/ResetPassword/__test__/updatePassword.spec.js
  src/containers/Auth/SocialAuth/__tests__/VerifyAuth.spec.js
  src/containers/Home/Home.js
  src/containers/Home/HomeLoader.js
  src/containers/Home/HomeLoader.scss
  src/containers/Home/__tests__/HomeLoader.spec.js
  src/containers/Reaction/__test__/likeReaction.spec.js
  src/helpers/utilities/utilities.js
  src/routes.js
Labels: merge first, ready

#25 #163457674 Show the user descriptive response and error messages
  src/components/Article/CreateArticle.js
  src/components/Article/__test__/CreatArticle.spec.js
  src/components/Article/articleConstants.js
  src/reducers/articleReducers/articleReducers.js
Labels: ready

#28 #161779834: implement functionality for users to follow authors
  src/actions/articleAction/__tests__/articleViewAction.spec.js
  src/actions/articleAction/actionTypes.js
  src/actions/articleAction/articleView.js
  src/actions/reactionActions/__test__/follow.spec.js
  src/actions/reactionActions/actionTypes.js
  src/actions/reactionActions/follow.js
  src/containers/Article/Article.js
  src/containers/Article/ArticleView.js
  src/containers/Article/ArticleView.scss
  src/containers/Article/__tests__/Article.spec.js
  src/containers/Article/__tests__/ArticleView.spec.js
  src/containers/Reaction/FollowReaction.js
  src/containers/Reaction/LikeReaction.js
  src/containers/Reaction/__test__/followReaction.test.js
  src/containers/Reaction/__test__/helpers.spec.js
  src/containers/Reaction/helpers.js
  src/containers/Reaction/helpers/reactionHelpers.js
  src/containers/Reaction/scss/reaction.scss
  src/reducers/articleViewReducer/__tests__/articleViewReducer.spec.js
  src/reducers/articleViewReducer/articleView.js
  src/reducers/index.js
  src/reducers/reactionReducers/__test__/follow.spec.js
  src/reducers/reactionReducers/follow.js
Labels: needs review

#30 #161779878 Implement the share article feature
  package-lock.json
  package.json
  src/components/misc/ShareBtn/ShareButton.js
  src/components/misc/ShareBtn/ShareButton.scss
  src/components/misc/ShareBtn/__tests__/ShareBtn.spec.js
  src/containers/Article/Article.js
  src/containers/Article/ArticleView.scss
  src/containers/Article/__tests__/Article.spec.js
  src/containers/Reaction/scss/reaction.scss
Labels: needs review, ready

#31 #163557852 add redirection to signup and signin pages
  config/webpack.prod.js
  jest.config.js
  package-lock.json
  src/actions/authAction/__test__/login.spec.js
  src/actions/authAction/login.js
  src/components/Article/CreateArticle.js
  src/components/misc/ShareBtn/ShareButton.js
  src/containers/App.js
  src/containers/Article/Article.js
  src/containers/Article/__tests__/Article.spec.js
  src/containers/Auth/Login/Login.js
  src/containers/Auth/Login/__test__/login.spec.js
  src/containers/Auth/SignUp/SignUp.js
  src/containers/Auth/SignUp/__test__/signUp.spec.js
  src/containers/Auth/SocialAuth/VerifyAuth.js
  src/containers/Auth/SocialAuth/__tests__/VerifyAuth.spec.js
  src/containers/Home/home.spec.js
  src/containers/Reaction/FollowReaction.js
  src/containers/Reaction/LikeReaction.js
  src/containers/Reaction/__test__/followReaction.test.js
  src/containers/Reaction/__test__/likeReaction.spec.js
  src/index.js
  src/reducers/__test__/login.spec.js
  src/reducers/authReducers/login.js
Labels: needs review, ready

#29 #163510396 Implement PO feedback from demo call
  package-lock.json
  src/assets/images/back 2.svg
  src/assets/images/back 3.svg
  src/assets/images/back 4.svg
  src/assets/images/back 5.svg
  src/assets/images/back.svg
  src/assets/images/icons/edit-3.svg
  src/assets/scss/base.scss
  src/assets/scss/base/_utilities.scss
  src/assets/scss/components/form/_form.scss
  src/assets/scss/components/navbar/_navbar.scss
  src/components/misc/Hero/Hero.js
  src/components/pages/NoMatch/NoMatch.scss
  src/components/utilities/BackDrop/BackDrop.js
  src/components/utilities/BackDrop/BackDrop.scss
  src/components/utilities/Card/Cards.scss
  src/components/utilities/Input/Input.js
  src/components/utilities/Navbar/Navbar.js
  src/components/utilities/Navbar/Navbar.scss
  src/containers/Auth/Login/_login.scss
  src/containers/Auth/ResetPassword/ResetPassword.scss
  src/containers/Auth/SignUp/SignUp.js
  src/containers/Auth/SignUp/__test__/signUp.spec.js
  src/containers/Auth/SignUp/style/signup.scss
  src/containers/Home/Home.js
  src/containers/Home/home.spec.js
  src/containers/UserProfile/UserProfile.js
  src/containers/UserProfile/_test_/userProfile.spec.js
  src/helpers/utilities/utilities.js
  src/index.html
Labels: needs review

#33 #161779828 user are able to rate articles
  src/actions/Ratings/AverageRatingActionCreators.js
  src/actions/Ratings/__test__/AverageRatingActionCreators.spec.js
  src/actions/Ratings/__test__/postRatingActionCreators.spec.js
  src/actions/Ratings/__test__/userRatingActionCreators.spec.js
  src/actions/Ratings/actionTypes.js
  src/actions/Ratings/postRatingActionCreators.js
  src/actions/Ratings/userRatingActionCreators.js
  src/assets/scss/base/_utilities.scss
  src/components/utilities/Card/Cards.scss
  src/containers/Article/Article.js
  src/containers/Article/ArticleView.js
  src/containers/Article/ArticleView.scss
  src/containers/Article/__tests__/ArticleView.spec.js
  src/containers/Comment/comment.scss
  src/containers/Home/Home.js
  src/containers/Ratings/Ratings.js
  src/containers/Ratings/__test__/Rating.spec.js
  src/containers/Reaction/likeReaction.scss
  src/reducers/index.js
  src/reducers/ratingsReducer/__test__/fetchAveargeRatings.spec.js
  src/reducers/ratingsReducer/__test__/fetchUserRatings.spec.js
  src/reducers/ratingsReducer/__test__/postRatings.spec.js
  src/reducers/ratingsReducer/fetchAveargeRatings.js
  src/reducers/ratingsReducer/fetchUserRatings.js
  src/reducers/ratingsReducer/postRatings.js
Labels: ready

#27 #161779826 implement users reading stats
  package-lock.json
  package.json
  src/actions/userStat/__test__/getUserStat.spec.js
  src/actions/userStat/actionTypes.js
  src/actions/userStat/getUserStat.js
  src/components/UserProfile/SideWidget/ProfileLinks.js
  src/components/UserProfile/SideWidget/SideWidget.js
  src/components/UserProfile/SideWidget/SideWidget.scss
  src/components/UserProfile/SideWidget/SideWidgetLinks/SideWidgetLink.js
  src/components/UserProfile/SideWidget/SideWidgetLinks/_test_/sideWidgetLink.spec.js
  src/components/UserProfile/SideWidget/__test__/sideWidgectLink.spec.js
  src/components/UserProfile/SideWidget/__test__/sideWidget.spec.js
  src/components/UserProfile/SideWidget/_test_/sideWidget.spec.js
  src/components/UserProfile/UpdateProfile/UpdateProfile.js
  src/components/UserProfile/UpdateProfile/_test_/updateProfile.spec.js
  src/components/UserProfile/UpdateProfile/_updateProfile.scss
  src/components/utilities/Card/ArticleParent.js
  src/components/utilities/Card/Cards.scss
  src/components/utilities/MiniCard/MiniCard.js
  src/components/utilities/MiniCard/_minicard.scss
  src/components/utilities/MiniCard/minicard.spec.js
  src/containers/UserProfile/UserProfile.js
  src/containers/UserProfile/_test_/userProfile.spec.js
  src/containers/UserProfile/_userprofile.scss
  src/containers/UserProfile/userStats/UserStatistics.js
  src/containers/UserProfile/userStats/_userStatistics.scss
  src/containers/UserProfile/userStats/userStatistics.spec.js
  src/index.html
  src/reducers/index.js
  src/reducers/userProfileReducers/Statistics.js
  src/reducers/userProfileReducers/_test_/statistics.spec.js
Labels: needs review, ready
